apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inventory-secret
  namespace: default

spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore

  target:
    name: inventory-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: eks/inventory-secrets
        property: DB_HOST

    - secretKey: DB_USER
      remoteRef:
        key: eks/inventory-secrets
        property: DB_USER

    - secretKey: DB_SSL
      remoteRef:
        key: eks/inventory-secrets
        property: DB_SSL

    - secretKey: DB_NAME
      remoteRef:
        key: eks/inventory-secrets
        property: DB_NAME
    - secretKey: PORT
      remoteRef:
        key: eks/inventory-secrets
        property: PORT
