apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
type: Opaque
stringData:
  DB_HOST: eks-rds-pg.cn0qc0uus9c0.ap-south-1.rds.amazonaws.com
  DB_USER: root
  DB_NAME: postgres
  DB_PORT: "5432"
  DB_SSL: "true"
  PORT: "3001"